// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the Game Data Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System;

namespace GameDataEditor
{
    public class GDEItemKeys
    {
        public static string WeaponAttribute_w1_mz_lv0 = "w1_mz_lv0";
        public static string WeaponAttribute_w1_mz_lv1 = "w1_mz_lv1";
        public static string WeaponAttribute_w1_mz_lv2 = "w1_mz_lv2";
        public static string WeaponAttribute_w1_st_lv0 = "w1_st_lv0";
        public static string WeaponAttribute_w1_st_lv1 = "w1_st_lv1";
        public static string WeaponAttribute_w1_st_lv2 = "w1_st_lv2";
        public static string WeaponAttribute_w1_cp_lv0 = "w1_cp_lv0";
        public static string WeaponAttribute_w1_cp_lv1 = "w1_cp_lv1";
        public static string WeaponAttribute_w1_cp_lv2 = "w1_cp_lv2";
        public static string WeaponAttribute_w1_sg_lv0 = "w1_sg_lv0";
        public static string WeaponAttribute_w1_sg_lv1 = "w1_sg_lv1";
        public static string WeaponAttribute_w1_sg_lv2 = "w1_sg_lv2";
        public static string WeaponAttribute_w1_ifa_lv0 = "w1_ifa_lv0";
        public static string WeaponComponent_w1_mz = "w1_mz";
        public static string WeaponComponent_w1_st = "w1_st";
        public static string WeaponComponent_w1_cp = "w1_cp";
        public static string WeaponComponent_w1_sg = "w1_sg";
        public static string WeaponComponent_w1_ifa = "w1_ifa";
        public static string Weapon_w1 = "w1";
    }
}
